
import { FoodCategory } from "@/types/diet";

// This component is responsible for providing food category data
export const foodCategoriesData: FoodCategory[] = [
  {
    name: "Meats & Poultry",
    items: [
      { id: "chicken_breast", name: "Chicken Breast (skinless)", protein: 31, carbs: 0, fats: 3.6, caloriesPerServing: 165, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "chicken_thigh_skinless", name: "Chicken Thigh (skinless)", protein: 26, carbs: 0, fats: 10, caloriesPerServing: 209, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "chicken_thigh_skin", name: "Chicken Thigh (with skin)", protein: 24, carbs: 0, fats: 15.5, caloriesPerServing: 229, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "chicken_wings", name: "Chicken Wings", protein: 30, carbs: 0, fats: 19, caloriesPerServing: 290, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "ground_turkey", name: "Ground Turkey (93% lean)", protein: 27, carbs: 0, fats: 8, caloriesPerServing: 170, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "beef_steak", name: "Beef Steak (sirloin)", protein: 26, carbs: 0, fats: 15, caloriesPerServing: 244, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "ground_beef_lean", name: "Ground Beef (90% lean)", protein: 26, carbs: 0, fats: 10, caloriesPerServing: 196, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "ground_beef_reg", name: "Ground Beef (80% lean)", protein: 25, carbs: 0, fats: 18, caloriesPerServing: 254, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "pork_chop", name: "Pork Chop (lean)", protein: 25, carbs: 0, fats: 7, caloriesPerServing: 175, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "bacon", name: "Bacon", protein: 37, carbs: 1, fats: 42, caloriesPerServing: 541, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "lamb", name: "Lamb (lean)", protein: 25, carbs: 0, fats: 16, caloriesPerServing: 258, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "veal_cutlet", name: "Veal Cutlet", protein: 29, carbs: 0, fats: 3.3, caloriesPerServing: 151, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "duck_breast", name: "Duck Breast (without skin)", protein: 23, carbs: 0, fats: 6, caloriesPerServing: 159, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "duck_leg", name: "Duck Leg", protein: 19, carbs: 0, fats: 21, caloriesPerServing: 265, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "goose", name: "Goose Meat", protein: 25, carbs: 0, fats: 12, caloriesPerServing: 209, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "rabbit", name: "Rabbit Meat", protein: 33, carbs: 0, fats: 3.5, caloriesPerServing: 173, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "venison", name: "Venison (deer)", protein: 30, carbs: 0, fats: 2.7, caloriesPerServing: 158, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "bison", name: "Bison/Buffalo Meat", protein: 28, carbs: 0, fats: 2, caloriesPerServing: 143, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "elk", name: "Elk Meat", protein: 31, carbs: 0, fats: 2, caloriesPerServing: 146, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "beef_liver", name: "Beef Liver", protein: 27, carbs: 3.9, fats: 3.6, caloriesPerServing: 175, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "chicken_liver", name: "Chicken Liver", protein: 26, carbs: 1, fats: 6, caloriesPerServing: 172, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "ground_pork", name: "Ground Pork", protein: 21, carbs: 0, fats: 20, caloriesPerServing: 263, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "pork_belly", name: "Pork Belly", protein: 9, carbs: 0, fats: 49, caloriesPerServing: 469, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "pork_shoulder", name: "Pork Shoulder", protein: 22, carbs: 0, fats: 12, caloriesPerServing: 196, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "pork_ribs", name: "Pork Ribs", protein: 27, carbs: 0, fats: 22, caloriesPerServing: 309, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "beef_brisket", name: "Beef Brisket", protein: 28, carbs: 0, fats: 12, caloriesPerServing: 218, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "beef_short_ribs", name: "Beef Short Ribs", protein: 28, carbs: 0, fats: 24, caloriesPerServing: 325, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "beef_ribeye", name: "Beef Ribeye Steak", protein: 27, carbs: 0, fats: 14, caloriesPerServing: 291, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "beef_t_bone", name: "T-Bone Steak", protein: 28, carbs: 0, fats: 17, caloriesPerServing: 267, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "beef_flank", name: "Beef Flank Steak", protein: 27, carbs: 0, fats: 6, caloriesPerServing: 194, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "beef_chuck", name: "Beef Chuck", protein: 26, carbs: 0, fats: 11, caloriesPerServing: 205, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "ostrich", name: "Ostrich Meat", protein: 26, carbs: 0, fats: 3, caloriesPerServing: 142, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "quail", name: "Quail Meat", protein: 25, carbs: 0, fats: 7, caloriesPerServing: 169, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "pheasant", name: "Pheasant Meat", protein: 27, carbs: 0, fats: 3.8, caloriesPerServing: 149, servingSize: "100g cooked", servingSizeGrams: 100 },
    ],
  },
  {
    name: "Fish & Seafood",
    items: [
      { id: "salmon", name: "Salmon (Atlantic)", protein: 25, carbs: 0, fats: 13, caloriesPerServing: 208, servingSize: "100g fillet", servingSizeGrams: 100 },
      { id: "salmon_smoked", name: "Smoked Salmon", protein: 24, carbs: 0, fats: 11, caloriesPerServing: 190, servingSize: "100g", servingSizeGrams: 100 },
      { id: "tuna", name: "Tuna (fresh)", protein: 30, carbs: 0, fats: 1, caloriesPerServing: 130, servingSize: "100g", servingSizeGrams: 100 },
      { id: "tuna_canned", name: "Tuna (canned in water)", protein: 26, carbs: 0, fats: 1, caloriesPerServing: 116, servingSize: "100g drained", servingSizeGrams: 100 },
      { id: "cod", name: "Cod", protein: 23, carbs: 0, fats: 1, caloriesPerServing: 105, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "tilapia", name: "Tilapia", protein: 26, carbs: 0, fats: 3, caloriesPerServing: 128, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "sardines", name: "Sardines (canned)", protein: 25, carbs: 0, fats: 11, caloriesPerServing: 208, servingSize: "100g drained", servingSizeGrams: 100 },
      { id: "shrimp", name: "Shrimp", protein: 24, carbs: 0, fats: 1, caloriesPerServing: 99, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "crab", name: "Crab", protein: 19, carbs: 0, fats: 1, caloriesPerServing: 97, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "haddock", name: "Haddock", protein: 20, carbs: 0, fats: 1, caloriesPerServing: 90, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "halibut", name: "Halibut", protein: 26, carbs: 0, fats: 2, caloriesPerServing: 119, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "sea_bass", name: "Sea Bass", protein: 24, carbs: 0, fats: 2, caloriesPerServing: 115, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "trout", name: "Trout", protein: 21, carbs: 0, fats: 8, caloriesPerServing: 162, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "mackerel", name: "Mackerel", protein: 20, carbs: 0, fats: 14, caloriesPerServing: 206, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "herring", name: "Herring", protein: 18, carbs: 0, fats: 14, caloriesPerServing: 203, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "anchovies", name: "Anchovies", protein: 29, carbs: 0, fats: 10, caloriesPerServing: 210, servingSize: "100g", servingSizeGrams: 100 },
      { id: "lobster", name: "Lobster", protein: 22, carbs: 1, fats: 0.5, caloriesPerServing: 98, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "scallops", name: "Scallops", protein: 21, carbs: 3, fats: 0.7, caloriesPerServing: 105, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "mussels", name: "Mussels", protein: 20, carbs: 5, fats: 2, caloriesPerServing: 129, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "clams", name: "Clams", protein: 17, carbs: 3, fats: 0.8, caloriesPerServing: 99, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "oysters", name: "Oysters", protein: 9, carbs: 5, fats: 2, caloriesPerServing: 80, servingSize: "100g", servingSizeGrams: 100 },
      { id: "squid", name: "Squid/Calamari", protein: 16, carbs: 3, fats: 1.2, caloriesPerServing: 92, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "octopus", name: "Octopus", protein: 25, carbs: 2, fats: 1, caloriesPerServing: 119, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "eel", name: "Eel", protein: 19, carbs: 0, fats: 18, caloriesPerServing: 236, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "swordfish", name: "Swordfish", protein: 25, carbs: 0, fats: 4, caloriesPerServing: 144, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "salmon_king", name: "King Salmon", protein: 26, carbs: 0, fats: 15, caloriesPerServing: 231, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "salmon_sockeye", name: "Sockeye Salmon", protein: 27, carbs: 0, fats: 11, caloriesPerServing: 200, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "salmon_coho", name: "Coho Salmon", protein: 24, carbs: 0, fats: 8, caloriesPerServing: 178, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "tuna_yellowfin", name: "Yellowfin Tuna", protein: 30, carbs: 0, fats: 1, caloriesPerServing: 130, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "tuna_albacore", name: "Albacore Tuna", protein: 29, carbs: 0, fats: 6, caloriesPerServing: 166, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "tuna_skipjack", name: "Skipjack Tuna", protein: 28, carbs: 0, fats: 1, caloriesPerServing: 132, servingSize: "100g cooked", servingSizeGrams: 100 },
    ],
  },
  {
    name: "Eggs & Dairy",
    items: [
      { id: "eggs_whole", name: "Eggs (whole)", protein: 13, carbs: 1, fats: 11, caloriesPerServing: 155, servingSize: "2 large eggs", servingSizeGrams: 100 },
      { id: "egg_whites", name: "Egg Whites", protein: 11, carbs: 1, fats: 0, caloriesPerServing: 52, servingSize: "100g (3 whites)", servingSizeGrams: 100 },
      { id: "greek_yogurt", name: "Greek Yogurt (plain, nonfat)", protein: 17, carbs: 6, fats: 0.7, caloriesPerServing: 100, servingSize: "170g container", servingSizeGrams: 170 },
      { id: "greek_yogurt_full", name: "Greek Yogurt (plain, full-fat)", protein: 15, carbs: 6, fats: 8, caloriesPerServing: 150, servingSize: "170g container", servingSizeGrams: 170 },
      { id: "cottage_cheese", name: "Cottage Cheese (2% fat)", protein: 25, carbs: 6, fats: 10, caloriesPerServing: 206, servingSize: "226g cup", servingSizeGrams: 226 },
      { id: "mozzarella", name: "Mozzarella Cheese", protein: 28, carbs: 3, fats: 22, caloriesPerServing: 318, servingSize: "100g", servingSizeGrams: 100 },
      { id: "cheddar", name: "Cheddar Cheese", protein: 25, carbs: 1, fats: 33, caloriesPerServing: 402, servingSize: "100g", servingSizeGrams: 100 },
      { id: "parmesan", name: "Parmesan Cheese", protein: 35, carbs: 4, fats: 28, caloriesPerServing: 420, servingSize: "100g", servingSizeGrams: 100 },
      { id: "milk", name: "Milk (2%)", protein: 8, carbs: 12, fats: 5, caloriesPerServing: 124, servingSize: "240ml cup", servingSizeGrams: 244 },
      { id: "milk_whole", name: "Whole Milk", protein: 8, carbs: 12, fats: 7.9, caloriesPerServing: 149, servingSize: "240ml cup", servingSizeGrams: 244 },
      { id: "milk_skim", name: "Skim Milk", protein: 8, carbs: 12, fats: 0.2, caloriesPerServing: 83, servingSize: "240ml cup", servingSizeGrams: 244 },
      { id: "milk_almond", name: "Almond Milk (unsweetened)", protein: 1, carbs: 1, fats: 2.5, caloriesPerServing: 30, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "milk_oat", name: "Oat Milk", protein: 3, carbs: 16, fats: 5, caloriesPerServing: 120, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "milk_soy", name: "Soy Milk (unsweetened)", protein: 7, carbs: 4, fats: 4, caloriesPerServing: 80, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "milk_coconut", name: "Coconut Milk", protein: 2, carbs: 2, fats: 4.5, caloriesPerServing: 45, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "cream_heavy", name: "Heavy Cream", protein: 2, carbs: 3, fats: 37, caloriesPerServing: 345, servingSize: "100g", servingSizeGrams: 100 },
      { id: "cream_sour", name: "Sour Cream", protein: 3, carbs: 3, fats: 19, caloriesPerServing: 193, servingSize: "100g", servingSizeGrams: 100 },
      { id: "cream_cheese", name: "Cream Cheese", protein: 6, carbs: 3, fats: 33, caloriesPerServing: 342, servingSize: "100g", servingSizeGrams: 100 },
      { id: "ricotta", name: "Ricotta Cheese", protein: 11, carbs: 3, fats: 10, caloriesPerServing: 174, servingSize: "100g", servingSizeGrams: 100 },
      { id: "feta", name: "Feta Cheese", protein: 14, carbs: 4, fats: 21, caloriesPerServing: 264, servingSize: "100g", servingSizeGrams: 100 },
      { id: "goat_cheese", name: "Goat Cheese", protein: 22, carbs: 2, fats: 30, caloriesPerServing: 364, servingSize: "100g", servingSizeGrams: 100 },
      { id: "brie", name: "Brie Cheese", protein: 21, carbs: 0.5, fats: 28, caloriesPerServing: 334, servingSize: "100g", servingSizeGrams: 100 },
      { id: "swiss", name: "Swiss Cheese", protein: 27, carbs: 5, fats: 28, caloriesPerServing: 380, servingSize: "100g", servingSizeGrams: 100 },
      { id: "provolone", name: "Provolone Cheese", protein: 26, carbs: 2, fats: 27, caloriesPerServing: 351, servingSize: "100g", servingSizeGrams: 100 },
      { id: "gorgonzola", name: "Gorgonzola Cheese", protein: 21, carbs: 2, fats: 32, caloriesPerServing: 375, servingSize: "100g", servingSizeGrams: 100 },
      { id: "cottage_cheese_1", name: "Cottage Cheese (1% fat)", protein: 12, carbs: 3, fats: 1, caloriesPerServing: 72, servingSize: "100g", servingSizeGrams: 100 },
      { id: "cottage_cheese_4", name: "Cottage Cheese (4% fat)", protein: 11, carbs: 3, fats: 4, caloriesPerServing: 98, servingSize: "100g", servingSizeGrams: 100 },
      { id: "egg_duck", name: "Duck Eggs", protein: 13, carbs: 1, fats: 15, caloriesPerServing: 185, servingSize: "70g egg", servingSizeGrams: 70 },
      { id: "egg_quail", name: "Quail Eggs", protein: 13, carbs: 1, fats: 11, caloriesPerServing: 158, servingSize: "50g (5 eggs)", servingSizeGrams: 50 },
      { id: "egg_goose", name: "Goose Eggs", protein: 14, carbs: 1, fats: 14, caloriesPerServing: 185, servingSize: "144g egg", servingSizeGrams: 144 },
    ],
  },
  {
    name: "Plant Proteins",
    items: [
      { id: "tofu_firm", name: "Tofu (firm)", protein: 8, carbs: 2, fats: 4, caloriesPerServing: 76, servingSize: "100g", servingSizeGrams: 100 },
      { id: "tofu_extra_firm", name: "Tofu (extra firm)", protein: 10, carbs: 2, fats: 5, caloriesPerServing: 86, servingSize: "100g", servingSizeGrams: 100 },
      { id: "tempeh", name: "Tempeh", protein: 19, carbs: 9, fats: 11, caloriesPerServing: 196, servingSize: "100g", servingSizeGrams: 100 },
      { id: "seitan", name: "Seitan", protein: 25, carbs: 4, fats: 1, caloriesPerServing: 130, servingSize: "100g", servingSizeGrams: 100 },
      { id: "black_beans", name: "Black Beans", protein: 8, carbs: 23, fats: 0.5, caloriesPerServing: 127, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "chickpeas", name: "Chickpeas", protein: 9, carbs: 27, fats: 2.5, caloriesPerServing: 164, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "lentils", name: "Lentils", protein: 18, carbs: 40, fats: 1, caloriesPerServing: 230, servingSize: "198g cooked cup", servingSizeGrams: 198 },
      { id: "edamame", name: "Edamame", protein: 11, carbs: 10, fats: 5, caloriesPerServing: 122, servingSize: "100g", servingSizeGrams: 100 },
      { id: "protein_powder", name: "Protein Powder (whey)", protein: 24, carbs: 3, fats: 1, caloriesPerServing: 120, servingSize: "30g scoop", servingSizeGrams: 30 },
      { id: "protein_powder_plant", name: "Protein Powder (plant-based)", protein: 21, carbs: 5, fats: 2, caloriesPerServing: 120, servingSize: "30g scoop", servingSizeGrams: 30 },
      { id: "tofu_silken", name: "Tofu (silken)", protein: 5, carbs: 2, fats: 3, caloriesPerServing: 55, servingSize: "100g", servingSizeGrams: 100 },
      { id: "tofu_soft", name: "Tofu (soft)", protein: 7, carbs: 2, fats: 4, caloriesPerServing: 68, servingSize: "100g", servingSizeGrams: 100 },
      { id: "miso", name: "Miso Paste", protein: 12, carbs: 18, fats: 6, caloriesPerServing: 174, servingSize: "100g", servingSizeGrams: 100 },
      { id: "natto", name: "Natto", protein: 19, carbs: 12, fats: 10, caloriesPerServing: 212, servingSize: "100g", servingSizeGrams: 100 },
      { id: "kidney_beans", name: "Kidney Beans", protein: 9, carbs: 22, fats: 0.5, caloriesPerServing: 127, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "pinto_beans", name: "Pinto Beans", protein: 9, carbs: 22, fats: 1, caloriesPerServing: 143, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "navy_beans", name: "Navy Beans", protein: 8, carbs: 24, fats: 0.6, caloriesPerServing: 140, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "red_lentils", name: "Red Lentils", protein: 9, carbs: 20, fats: 0.4, caloriesPerServing: 116, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "green_lentils", name: "Green Lentils", protein: 9, carbs: 20, fats: 0.4, caloriesPerServing: 116, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "french_lentils", name: "French Lentils", protein: 9, carbs: 20, fats: 0.4, caloriesPerServing: 116, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "soybeans", name: "Soybeans", protein: 18, carbs: 8, fats: 9, caloriesPerServing: 173, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "peas", name: "Green Peas", protein: 5, carbs: 14, fats: 0.4, caloriesPerServing: 81, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "split_peas", name: "Split Peas", protein: 8, carbs: 21, fats: 0.4, caloriesPerServing: 118, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "lupini_beans", name: "Lupini Beans", protein: 16, carbs: 10, fats: 3, caloriesPerServing: 119, servingSize: "100g", servingSizeGrams: 100 },
      { id: "fava_beans", name: "Fava Beans", protein: 8, carbs: 16, fats: 0.7, caloriesPerServing: 110, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "lima_beans", name: "Lima Beans", protein: 8, carbs: 21, fats: 0.4, caloriesPerServing: 115, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "adzuki_beans", name: "Adzuki Beans", protein: 7, carbs: 25, fats: 0.2, caloriesPerServing: 128, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "mung_beans", name: "Mung Beans", protein: 7, carbs: 16, fats: 0.4, caloriesPerServing: 105, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "black_eyed_peas", name: "Black-eyed Peas", protein: 5, carbs: 16, fats: 0.6, caloriesPerServing: 116, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "tofu_fried", name: "Fried Tofu", protein: 19, carbs: 10, fats: 25, caloriesPerServing: 271, servingSize: "100g", servingSizeGrams: 100 },
    ],
  },
  {
    name: "Grains & Pastas",
    items: [
      { id: "white_rice", name: "White Rice", protein: 4, carbs: 45, fats: 0.4, caloriesPerServing: 200, servingSize: "158g cooked cup", servingSizeGrams: 158 },
      { id: "brown_rice", name: "Brown Rice", protein: 5, carbs: 46, fats: 1.8, caloriesPerServing: 216, servingSize: "195g cooked cup", servingSizeGrams: 195 },
      { id: "jasmine_rice", name: "Jasmine Rice", protein: 4, carbs: 45, fats: 0.4, caloriesPerServing: 205, servingSize: "158g cooked cup", servingSizeGrams: 158 },
      { id: "basmati_rice", name: "Basmati Rice", protein: 5, carbs: 45, fats: 0.5, caloriesPerServing: 205, servingSize: "158g cooked cup", servingSizeGrams: 158 },
      { id: "quinoa", name: "Quinoa", protein: 8, carbs: 39, fats: 4, caloriesPerServing: 222, servingSize: "185g cooked cup", servingSizeGrams: 185 },
      { id: "couscous", name: "Couscous", protein: 6, carbs: 36, fats: 0.3, caloriesPerServing: 176, servingSize: "157g cooked cup", servingSizeGrams: 157 },
      { id: "pasta_regular", name: "Pasta (white)", protein: 7, carbs: 43, fats: 1, caloriesPerServing: 200, servingSize: "140g cooked cup", servingSizeGrams: 140 },
      { id: "pasta_whole_wheat", name: "Pasta (whole wheat)", protein: 8, carbs: 37, fats: 1, caloriesPerServing: 174, servingSize: "140g cooked cup", servingSizeGrams: 140 },
      { id: "pasta_chickpea", name: "Pasta (chickpea)", protein: 14, carbs: 32, fats: 2, caloriesPerServing: 190, servingSize: "140g cooked cup", servingSizeGrams: 140 },
      { id: "pasta_lentil", name: "Pasta (red lentil)", protein: 13, carbs: 31, fats: 1, caloriesPerServing: 180, servingSize: "140g cooked cup", servingSizeGrams: 140 },
      { id: "barley", name: "Barley", protein: 3.5, carbs: 28, fats: 0.7, caloriesPerServing: 123, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "bulgur", name: "Bulgur Wheat", protein: 3.1, carbs: 19, fats: 0.2, caloriesPerServing: 83, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "millet", name: "Millet", protein: 3.5, carbs: 23, fats: 1, caloriesPerServing: 119, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "farro", name: "Farro", protein: 6, carbs: 26, fats: 1, caloriesPerServing: 127, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "black_rice", name: "Black/Forbidden Rice", protein: 5, carbs: 34, fats: 1.5, caloriesPerServing: 160, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "rice_wild", name: "Wild Rice", protein: 4, carbs: 21, fats: 0.3, caloriesPerServing: 101, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "arborio_rice", name: "Arborio Rice", protein: 2.5, carbs: 28, fats: 0.2, caloriesPerServing: 130, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "sushi_rice", name: "Sushi Rice", protein: 3, carbs: 30, fats: 0.1, caloriesPerServing: 130, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "rice_noodles", name: "Rice Noodles", protein: 1.8, carbs: 25, fats: 0.2, caloriesPerServing: 109, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "soba_noodles", name: "Soba Noodles", protein: 5.8, carbs: 24, fats: 0.1, caloriesPerServing: 113, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "udon_noodles", name: "Udon Noodles", protein: 3, carbs: 28, fats: 0.1, caloriesPerServing: 115, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "egg_noodles", name: "Egg Noodles", protein: 4.5, carbs: 25, fats: 2, caloriesPerServing: 138, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "ramen_noodles", name: "Ramen Noodles", protein: 4.5, carbs: 26, fats: 7, caloriesPerServing: 188, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "orzo", name: "Orzo", protein: 5, carbs: 29, fats: 0.3, caloriesPerServing: 130, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "semolina", name: "Semolina", protein: 13, carbs: 73, fats: 1.2, caloriesPerServing: 360, servingSize: "100g dry", servingSizeGrams: 100 },
      { id: "amaranth", name: "Amaranth", protein: 9, carbs: 65, fats: 6, caloriesPerServing: 370, servingSize: "100g dry", servingSizeGrams: 100 },
      { id: "teff", name: "Teff", protein: 13, carbs: 73, fats: 2, caloriesPerServing: 367, servingSize: "100g dry", servingSizeGrams: 100 },
      { id: "freekeh", name: "Freekeh", protein: 13, carbs: 43, fats: 1.9, caloriesPerServing: 325, servingSize: "100g dry", servingSizeGrams: 100 },
      { id: "buckwheat", name: "Buckwheat", protein: 13, carbs: 70, fats: 3.4, caloriesPerServing: 343, servingSize: "100g dry", servingSizeGrams: 100 },
      { id: "kamut", name: "Kamut", protein: 15, carbs: 70, fats: 2.2, caloriesPerServing: 337, servingSize: "100g dry", servingSizeGrams: 100 },
    ],
  },
  {
    name: "Starchy Vegetables",
    items: [
      { id: "sweet_potato", name: "Sweet Potato", protein: 2, carbs: 26, fats: 0.1, caloriesPerServing: 112, servingSize: "130g medium", servingSizeGrams: 130 },
      { id: "potatoes", name: "Potatoes (white)", protein: 2, carbs: 17, fats: 0.1, caloriesPerServing: 77, servingSize: "100g boiled", servingSizeGrams: 100 },
      { id: "potatoes_sweet", name: "Sweet Potatoes", protein: 2, carbs: 20, fats: 0.1, caloriesPerServing: 90, servingSize: "100g baked", servingSizeGrams: 100 },
      { id: "corn", name: "Corn", protein: 3.3, carbs: 25, fats: 1.4, caloriesPerServing: 125, servingSize: "100g", servingSizeGrams: 100 },
      { id: "peas", name: "Green Peas", protein: 5, carbs: 14, fats: 0.4, caloriesPerServing: 81, servingSize: "100g", servingSizeGrams: 100 },
      { id: "butternut_squash", name: "Butternut Squash", protein: 1, carbs: 12, fats: 0.1, caloriesPerServing: 45, servingSize: "100g", servingSizeGrams: 100 },
      { id: "acorn_squash", name: "Acorn Squash", protein: 1, carbs: 15, fats: 0.1, caloriesPerServing: 56, servingSize: "100g", servingSizeGrams: 100 },
      { id: "potatoes_red", name: "Red Potatoes", protein: 2, carbs: 17, fats: 0.1, caloriesPerServing: 75, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "potatoes_yukon", name: "Yukon Gold Potatoes", protein: 2, carbs: 16, fats: 0.1, caloriesPerServing: 73, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "potatoes_purple", name: "Purple Potatoes", protein: 2, carbs: 17, fats: 0.1, caloriesPerServing: 77, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "potatoes_russet", name: "Russet Potatoes", protein: 2, carbs: 21, fats: 0.1, caloriesPerServing: 94, servingSize: "100g baked", servingSizeGrams: 100 },
      { id: "plantains", name: "Plantains", protein: 1.3, carbs: 32, fats: 0.4, caloriesPerServing: 148, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "parsnips", name: "Parsnips", protein: 1.2, carbs: 18, fats: 0.3, caloriesPerServing: 75, servingSize: "100g", servingSizeGrams: 100 },
      { id: "taro", name: "Taro Root", protein: 0.6, carbs: 22, fats: 0.2, caloriesPerServing: 112, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "cassava", name: "Cassava/Yuca", protein: 1.4, carbs: 38, fats: 0.3, caloriesPerServing: 160, servingSize: "100g", servingSizeGrams: 100 },
      { id: "yams", name: "Yams", protein: 2, carbs: 28, fats: 0.1, caloriesPerServing: 118, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "beets", name: "Beets", protein: 1.6, carbs: 10, fats: 0.2, caloriesPerServing: 44, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "rutabaga", name: "Rutabaga", protein: 1.2, carbs: 8, fats: 0.2, caloriesPerServing: 38, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "turnips", name: "Turnips", protein: 0.9, carbs: 6, fats: 0.1, caloriesPerServing: 28, servingSize: "100g cooked", servingSizeGrams: 100 },
      { id: "water_chestnuts", name: "Water Chestnuts", protein: 0.9, carbs: 24, fats: 0.1, caloriesPerServing: 97, servingSize: "100g", servingSizeGrams: 100 },
      { id: "jicama", name: "Jicama", protein: 0.9, carbs: 9, fats: 0.1, caloriesPerServing: 38, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "kabocha_squash", name: "Kabocha Squash", protein: 1.8, carbs: 7, fats: 0.1, caloriesPerServing: 30, servingSize: "100g", servingSizeGrams: 100 },
      { id: "delicata_squash", name: "Delicata Squash", protein: 1, carbs: 10, fats: 0.1, caloriesPerServing: 40, servingSize: "100g", servingSizeGrams: 100 },
      { id: "spaghetti_squash", name: "Spaghetti Squash", protein: 0.6, carbs: 7, fats: 0.4, caloriesPerServing: 31, servingSize: "100g cooked", servingSizeGrams: 100 },
    ],
  },
  {
    name: "Breads & Breakfast",
    items: [
      { id: "whole_wheat_bread", name: "Whole Wheat Bread", protein: 4, carbs: 13, fats: 1, caloriesPerServing: 69, servingSize: "28g slice", servingSizeGrams: 28 },
      { id: "white_bread", name: "White Bread", protein: 3, carbs: 14, fats: 1, caloriesPerServing: 77, servingSize: "28g slice", servingSizeGrams: 28 },
      { id: "ezekiel_bread", name: "Ezekiel Bread", protein: 4, carbs: 15, fats: 0.5, caloriesPerServing: 80, servingSize: "34g slice", servingSizeGrams: 34 },
      { id: "bagel", name: "Bagel", protein: 10, carbs: 53, fats: 1, caloriesPerServing: 270, servingSize: "105g bagel", servingSizeGrams: 105 },
      { id: "english_muffin", name: "English Muffin", protein: 4, carbs: 25, fats: 1, caloriesPerServing: 130, servingSize: "57g muffin", servingSizeGrams: 57 },
      { id: "tortilla_corn", name: "Corn Tortilla", protein: 1, carbs: 11, fats: 0.5, caloriesPerServing: 52, servingSize: "30g (6 inch)", servingSizeGrams: 30 },
      { id: "tortilla_flour", name: "Flour Tortilla", protein: 3, carbs: 15, fats: 3, caloriesPerServing: 100, servingSize: "30g (6 inch)", servingSizeGrams: 30 },
      { id: "oats", name: "Oats (rolled)", protein: 13, carbs: 67, fats: 7, caloriesPerServing: 389, servingSize: "100g dry", servingSizeGrams: 100 },
      { id: "oats_steel", name: "Oats (steel cut)", protein: 13, carbs: 67, fats: 7, caloriesPerServing: 379, servingSize: "100g dry", servingSizeGrams: 100 },
      { id: "cereal", name: "Cereal (low sugar)", protein: 7, carbs: 74, fats: 2, caloriesPerServing: 380, servingSize: "100g", servingSizeGrams: 100 },
      { id: "sourdough_bread", name: "Sourdough Bread", protein: 4, carbs: 15, fats: 0.5, caloriesPerServing: 80, servingSize: "32g slice", servingSizeGrams: 32 },
      { id: "rye_bread", name: "Rye Bread", protein: 3, carbs: 15, fats: 0.6, caloriesPerServing: 83, servingSize: "32g slice", servingSizeGrams: 32 },
      { id: "pita_bread", name: "Pita Bread", protein: 3, carbs: 17, fats: 0.4, caloriesPerServing: 85, servingSize: "30g small", servingSizeGrams: 30 },
      { id: "naan_bread", name: "Naan Bread", protein: 4, carbs: 29, fats: 5, caloriesPerServing: 180, servingSize: "57g piece", servingSizeGrams: 57 },
      { id: "focaccia", name: "Focaccia", protein: 5, carbs: 29, fats: 9, caloriesPerServing: 220, servingSize: "65g piece", servingSizeGrams: 65 },
      { id: "ciabatta", name: "Ciabatta", protein: 6, carbs: 30, fats: 1.5, caloriesPerServing: 160, servingSize: "50g slice", servingSizeGrams: 50 },
      { id: "croissant", name: "Croissant", protein: 5, carbs: 26, fats: 12, caloriesPerServing: 230, servingSize: "60g", servingSizeGrams: 60 },
      { id: "granola", name: "Granola", protein: 8, carbs: 65, fats: 13, caloriesPerServing: 400, servingSize: "100g", servingSizeGrams: 100 },
      { id: "muesli", name: "Muesli", protein: 13, carbs: 69, fats: 8, caloriesPerServing: 394, servingSize: "100g", servingSizeGrams: 100 },
      { id: "cereal_bran", name: "Bran Cereal", protein: 8, carbs: 58, fats: 4, caloriesPerServing: 300, servingSize: "100g", servingSizeGrams: 100 },
      { id: "waffles", name: "Waffles", protein: 6, carbs: 25, fats: 10, caloriesPerServing: 210, servingSize: "75g (2 waffles)", servingSizeGrams: 75 },
      { id: "pancakes", name: "Pancakes", protein: 5, carbs: 28, fats: 9, caloriesPerServing: 210, servingSize: "80g (2 pancakes)", servingSizeGrams: 80 },
      { id: "french_toast", name: "French Toast", protein: 8, carbs: 25, fats: 7, caloriesPerServing: 193, servingSize: "82g (2 slices)", servingSizeGrams: 82 },
      { id: "oatmeal", name: "Oatmeal (cooked)", protein: 5, carbs: 27, fats: 3, caloriesPerServing: 158, servingSize: "234g cup", servingSizeGrams: 234 },
      { id: "bread_potato", name: "Potato Bread", protein: 4, carbs: 16, fats: 2, caloriesPerServing: 97, servingSize: "35g slice", servingSizeGrams: 35 },
      { id: "tortilla_whole_wheat", name: "Whole Wheat Tortilla", protein: 3, carbs: 15, fats: 3, caloriesPerServing: 100, servingSize: "30g (6 inch)", servingSizeGrams: 30 },
      { id: "flatbread", name: "Flatbread", protein: 4, carbs: 26, fats: 2, caloriesPerServing: 142, servingSize: "50g piece", servingSizeGrams: 50 },
      { id: "crepes", name: "Crepes", protein: 4, carbs: 13, fats: 3, caloriesPerServing: 97, servingSize: "50g crepe", servingSizeGrams: 50 },
      { id: "oats_instant", name: "Instant Oats", protein: 13, carbs: 67, fats: 7, caloriesPerServing: 389, servingSize: "100g dry", servingSizeGrams: 100 },
      { id: "breadcrumbs", name: "Breadcrumbs", protein: 10, carbs: 75, fats: 4, caloriesPerServing: 380, servingSize: "100g", servingSizeGrams: 100 },
    ],
  },
  {
    name: "Green Vegetables",
    items: [
      { id: "broccoli", name: "Broccoli", protein: 2.6, carbs: 6, fats: 0.3, caloriesPerServing: 34, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "spinach", name: "Spinach", protein: 2.9, carbs: 3.6, fats: 0.4, caloriesPerServing: 23, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "kale", name: "Kale", protein: 2.9, carbs: 6.7, fats: 0.5, caloriesPerServing: 35, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "bok_choy", name: "Bok Choy", protein: 1.5, carbs: 2.2, fats: 0.2, caloriesPerServing: 13, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "collard_greens", name: "Collard Greens", protein: 2, carbs: 5.7, fats: 0.5, caloriesPerServing: 32, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "brussels_sprouts", name: "Brussels Sprouts", protein: 3.4, carbs: 9, fats: 0.3, caloriesPerServing: 43, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "asparagus", name: "Asparagus", protein: 2.2, carbs: 3.9, fats: 0.1, caloriesPerServing: 20, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "green_beans", name: "Green Beans", protein: 1.8, carbs: 7, fats: 0.1, caloriesPerServing: 31, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "arugula", name: "Arugula", protein: 2.6, carbs: 3.7, fats: 0.7, caloriesPerServing: 25, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "romaine", name: "Romaine Lettuce", protein: 1.2, carbs: 3.3, fats: 0.3, caloriesPerServing: 17, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "iceberg", name: "Iceberg Lettuce", protein: 0.9, carbs: 2.9, fats: 0.1, caloriesPerServing: 14, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "cabbage_green", name: "Green Cabbage", protein: 1.3, carbs: 5.8, fats: 0.1, caloriesPerServing: 25, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "cabbage_red", name: "Red Cabbage", protein: 1.4, carbs: 7, fats: 0.2, caloriesPerServing: 31, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "swiss_chard", name: "Swiss Chard", protein: 1.8, carbs: 3.7, fats: 0.2, caloriesPerServing: 19, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "beet_greens", name: "Beet Greens", protein: 2.2, carbs: 4.3, fats: 0.1, caloriesPerServing: 22, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "watercress", name: "Watercress", protein: 2.3, carbs: 1.3, fats: 0.1, caloriesPerServing: 11, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "mustard_greens", name: "Mustard Greens", protein: 2.7, carbs: 4.7, fats: 0.2, caloriesPerServing: 27, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "turnip_greens", name: "Turnip Greens", protein: 1.1, carbs: 3.9, fats: 0.2, caloriesPerServing: 20, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "dandelion_greens", name: "Dandelion Greens", protein: 2.7, carbs: 9, fats: 0.7, caloriesPerServing: 45, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "endive", name: "Endive", protein: 1.3, carbs: 3.4, fats: 0.2, caloriesPerServing: 17, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "escarole", name: "Escarole", protein: 1.5, carbs: 3.1, fats: 0.2, caloriesPerServing: 17, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "radicchio", name: "Radicchio", protein: 1.3, carbs: 4.5, fats: 0.2, caloriesPerServing: 23, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "broccoli_rabe", name: "Broccoli Rabe", protein: 3.2, carbs: 2.9, fats: 0.5, caloriesPerServing: 28, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "microgreens", name: "Microgreens", protein: 3.5, carbs: 5.5, fats: 0.4, caloriesPerServing: 40, servingSize: "100g raw", servingSizeGrams: 100 },
    ],
  },
  {
    name: "Other Vegetables",
    items: [
      { id: "bell_peppers", name: "Bell Peppers", protein: 1, carbs: 6, fats: 0.3, caloriesPerServing: 30, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "cucumber", name: "Cucumber", protein: 0.7, carbs: 3.6, fats: 0.1, caloriesPerServing: 16, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "carrots", name: "Carrots", protein: 0.9, carbs: 10, fats: 0.2, caloriesPerServing: 41, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "zucchini", name: "Zucchini", protein: 1.2, carbs: 3.9, fats: 0.3, caloriesPerServing: 20, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "tomatoes", name: "Tomatoes", protein: 0.9, carbs: 3.9, fats: 0.2, caloriesPerServing: 18, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "mushrooms", name: "Mushrooms", protein: 3, carbs: 3, fats: 0.3, caloriesPerServing: 22, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "onions", name: "Onions", protein: 1.1, carbs: 9.3, fats: 0.1, caloriesPerServing: 40, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "cauliflower", name: "Cauliflower", protein: 1.9, carbs: 5, fats: 0.3, caloriesPerServing: 25, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "eggplant", name: "Eggplant", protein: 1, carbs: 6, fats: 0.2, caloriesPerServing: 25, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "celery", name: "Celery", protein: 0.7, carbs: 3.4, fats: 0.2, caloriesPerServing: 16, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "radishes", name: "Radishes", protein: 0.7, carbs: 3.4, fats: 0.1, caloriesPerServing: 16, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "artichokes", name: "Artichokes", protein: 3.3, carbs: 10.5, fats: 0.2, caloriesPerServing: 47, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "fennel", name: "Fennel", protein: 1.2, carbs: 7.3, fats: 0.2, caloriesPerServing: 31, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "leeks", name: "Leeks", protein: 1.5, carbs: 14, fats: 0.3, caloriesPerServing: 61, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "kohlrabi", name: "Kohlrabi", protein: 1.7, carbs: 6.2, fats: 0.1, caloriesPerServing: 27, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "okra", name: "Okra", protein: 1.9, carbs: 7.5, fats: 0.2, caloriesPerServing: 33, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "pumpkin", name: "Pumpkin", protein: 1, carbs: 7, fats: 0.1, caloriesPerServing: 26, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "snow_peas", name: "Snow Peas", protein: 2.8, carbs: 7.5, fats: 0.2, caloriesPerServing: 42, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "snap_peas", name: "Snap Peas", protein: 2.8, carbs: 7.5, fats: 0.2, caloriesPerServing: 42, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "garlic", name: "Garlic", protein: 6.4, carbs: 33, fats: 0.5, caloriesPerServing: 149, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "shallots", name: "Shallots", protein: 2.5, carbs: 17, fats: 0.1, caloriesPerServing: 72, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "scallions", name: "Scallions/Green Onions", protein: 1.8, carbs: 7, fats: 0.2, caloriesPerServing: 32, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "chives", name: "Chives", protein: 3.3, carbs: 4.4, fats: 0.7, caloriesPerServing: 30, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "rhubarb", name: "Rhubarb", protein: 0.9, carbs: 5.5, fats: 0.2, caloriesPerServing: 21, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "mushrooms_shiitake", name: "Shiitake Mushrooms", protein: 2.2, carbs: 6.8, fats: 0.3, caloriesPerServing: 34, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "mushrooms_portobello", name: "Portobello Mushrooms", protein: 3.3, carbs: 4.3, fats: 0.4, caloriesPerServing: 29, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "mushrooms_oyster", name: "Oyster Mushrooms", protein: 3.3, carbs: 6.5, fats: 0.4, caloriesPerServing: 35, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "cherry_tomatoes", name: "Cherry Tomatoes", protein: 0.9, carbs: 3.9, fats: 0.2, caloriesPerServing: 18, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "roma_tomatoes", name: "Roma Tomatoes", protein: 0.9, carbs: 3.9, fats: 0.2, caloriesPerServing: 18, servingSize: "100g raw", servingSizeGrams: 100 },
      { id: "squash_yellow", name: "Yellow Squash", protein: 1.2, carbs: 3.4, fats: 0.2, caloriesPerServing: 19, servingSize: "100g raw", servingSizeGrams: 100 },
    ],
  },
  {
    name: "Fruits",
    items: [
      { id: "banana", name: "Banana", protein: 1.1, carbs: 23, fats: 0.3, caloriesPerServing: 96, servingSize: "118g medium", servingSizeGrams: 118 },
      { id: "apple", name: "Apple", protein: 0.3, carbs: 14, fats: 0.2, caloriesPerServing: 59, servingSize: "100g medium", servingSizeGrams: 100 },
      { id: "berries_mixed", name: "Mixed Berries", protein: 0.7, carbs: 14, fats: 0.3, caloriesPerServing: 57, servingSize: "100g", servingSizeGrams: 100 },
      { id: "strawberries", name: "Strawberries", protein: 0.7, carbs: 7.7, fats: 0.3, caloriesPerServing: 32, servingSize: "100g", servingSizeGrams: 100 },
      { id: "blueberries", name: "Blueberries", protein: 0.7, carbs: 14, fats: 0.3, caloriesPerServing: 57, servingSize: "100g", servingSizeGrams: 100 },
      { id: "blackberries", name: "Blackberries", protein: 1.4, carbs: 10, fats: 0.4, caloriesPerServing: 43, servingSize: "100g", servingSizeGrams: 100 },
      { id: "raspberries", name: "Raspberries", protein: 1.2, carbs: 12, fats: 0.7, caloriesPerServing: 52, servingSize: "100g", servingSizeGrams: 100 },
      { id: "orange", name: "Orange", protein: 1.2, carbs: 12, fats: 0.2, caloriesPerServing: 62, servingSize: "131g medium", servingSizeGrams: 131 },
      { id: "avocado", name: "Avocado", protein: 2, carbs: 12, fats: 15, caloriesPerServing: 160, servingSize: "100g (1/2 medium)", servingSizeGrams: 100 },
      { id: "mango", name: "Mango", protein: 0.8, carbs: 15, fats: 0.3, caloriesPerServing: 60, servingSize: "100g", servingSizeGrams: 100 },
      { id: "pineapple", name: "Pineapple", protein: 0.5, carbs: 13, fats: 0.1, caloriesPerServing: 50, servingSize: "100g", servingSizeGrams: 100 },
      { id: "grapes", name: "Grapes", protein: 0.6, carbs: 17, fats: 0.3, caloriesPerServing: 69, servingSize: "100g", servingSizeGrams: 100 },
      { id: "peach", name: "Peach", protein: 0.9, carbs: 10, fats: 0.3, caloriesPerServing: 42, servingSize: "100g", servingSizeGrams: 100 },
      { id: "pear", name: "Pear", protein: 0.4, carbs: 15, fats: 0.1, caloriesPerServing: 58, servingSize: "100g", servingSizeGrams: 100 },
      { id: "kiwi", name: "Kiwi", protein: 1.1, carbs: 15, fats: 0.5, caloriesPerServing: 61, servingSize: "100g", servingSizeGrams: 100 },
      { id: "plum", name: "Plum", protein: 0.7, carbs: 11, fats: 0.3, caloriesPerServing: 46, servingSize: "100g", servingSizeGrams: 100 },
      { id: "apricot", name: "Apricot", protein: 1.4, carbs: 11, fats: 0.4, caloriesPerServing: 48, servingSize: "100g", servingSizeGrams: 100 },
      { id: "cantaloupe", name: "Cantaloupe", protein: 0.8, carbs: 8, fats: 0.2, caloriesPerServing: 34, servingSize: "100g", servingSizeGrams: 100 },
      { id: "honeydew", name: "Honeydew Melon", protein: 0.5, carbs: 9, fats: 0.1, caloriesPerServing: 36, servingSize: "100g", servingSizeGrams: 100 },
      { id: "watermelon", name: "Watermelon", protein: 0.6, carbs: 8, fats: 0.2, caloriesPerServing: 30, servingSize: "100g", servingSizeGrams: 100 },
      { id: "cherries", name: "Cherries", protein: 1, carbs: 16, fats: 0.3, caloriesPerServing: 63, servingSize: "100g", servingSizeGrams: 100 },
      { id: "papaya", name: "Papaya", protein: 0.5, carbs: 10, fats: 0.3, caloriesPerServing: 43, servingSize: "100g", servingSizeGrams: 100 },
      { id: "pomegranate", name: "Pomegranate", protein: 1.7, carbs: 19, fats: 1.2, caloriesPerServing: 83, servingSize: "100g", servingSizeGrams: 100 },
      { id: "guava", name: "Guava", protein: 2.6, carbs: 14, fats: 1, caloriesPerServing: 68, servingSize: "100g", servingSizeGrams: 100 },
      { id: "lychee", name: "Lychee", protein: 0.8, carbs: 17, fats: 0.4, caloriesPerServing: 66, servingSize: "100g", servingSizeGrams: 100 },
      { id: "passionfruit", name: "Passionfruit", protein: 2.2, carbs: 13, fats: 0.7, caloriesPerServing: 68, servingSize: "100g", servingSizeGrams: 100 },
      { id: "dragonfruit", name: "Dragon Fruit", protein: 1.1, carbs: 13, fats: 0.4, caloriesPerServing: 60, servingSize: "100g", servingSizeGrams: 100 },
      { id: "fig", name: "Figs", protein: 0.8, carbs: 19, fats: 0.3, caloriesPerServing: 74, servingSize: "100g", servingSizeGrams: 100 },
      { id: "dates", name: "Dates", protein: 2.5, carbs: 75, fats: 0.4, caloriesPerServing: 277, servingSize: "100g", servingSizeGrams: 100 },
      { id: "prunes", name: "Prunes", protein: 2.2, carbs: 64, fats: 0.4, caloriesPerServing: 240, servingSize: "100g", servingSizeGrams: 100 },
      { id: "raisins", name: "Raisins", protein: 3.1, carbs: 79, fats: 0.5, caloriesPerServing: 299, servingSize: "100g", servingSizeGrams: 100 },
      { id: "cranberries", name: "Cranberries", protein: 0.4, carbs: 12, fats: 0.1, caloriesPerServing: 46, servingSize: "100g", servingSizeGrams: 100 },
      { id: "grapefruit", name: "Grapefruit", protein: 0.8, carbs: 11, fats: 0.1, caloriesPerServing: 42, servingSize: "100g", servingSizeGrams: 100 },
      { id: "lime", name: "Lime", protein: 0.7, carbs: 10, fats: 0.2, caloriesPerServing: 30, servingSize: "100g", servingSizeGrams: 100 },
      { id: "lemon", name: "Lemon", protein: 1.1, carbs: 9, fats: 0.3, caloriesPerServing: 29, servingSize: "100g", servingSizeGrams: 100 },
    ],
  },
  {
    name: "Nuts & Seeds",
    items: [
      { id: "almonds", name: "Almonds", protein: 21, carbs: 22, fats: 49, caloriesPerServing: 579, servingSize: "100g", servingSizeGrams: 100 },
      { id: "walnuts", name: "Walnuts", protein: 15, carbs: 14, fats: 65, caloriesPerServing: 654, servingSize: "100g", servingSizeGrams: 100 },
      { id: "cashews", name: "Cashews", protein: 18, carbs: 30, fats: 44, caloriesPerServing: 553, servingSize: "100g", servingSizeGrams: 100 },
      { id: "pistachios", name: "Pistachios", protein: 20, carbs: 28, fats: 45, caloriesPerServing: 560, servingSize: "100g", servingSizeGrams: 100 },
      { id: "pecans", name: "Pecans", protein: 9, carbs: 14, fats: 72, caloriesPerServing: 691, servingSize: "100g", servingSizeGrams: 100 },
      { id: "hazelnuts", name: "Hazelnuts", protein: 15, carbs: 17, fats: 61, caloriesPerServing: 628, servingSize: "100g", servingSizeGrams: 100 },
      { id: "macadamia", name: "Macadamia Nuts", protein: 8, carbs: 14, fats: 76, caloriesPerServing: 718, servingSize: "100g", servingSizeGrams: 100 },
      { id: "brazil_nuts", name: "Brazil Nuts", protein: 14, carbs: 12, fats: 66, caloriesPerServing: 656, servingSize: "100g", servingSizeGrams: 100 },
      { id: "pine_nuts", name: "Pine Nuts", protein: 14, carbs: 13, fats: 68, caloriesPerServing: 673, servingSize: "100g", servingSizeGrams: 100 },
      { id: "sunflower_seeds", name: "Sunflower Seeds", protein: 21, carbs: 20, fats: 51, caloriesPerServing: 584, servingSize: "100g", servingSizeGrams: 100 },
      { id: "pumpkin_seeds", name: "Pumpkin Seeds", protein: 30, carbs: 10, fats: 49, caloriesPerServing: 559, servingSize: "100g", servingSizeGrams: 100 },
      { id: "chia_seeds", name: "Chia Seeds", protein: 17, carbs: 42, fats: 31, caloriesPerServing: 486, servingSize: "100g", servingSizeGrams: 100 },
      { id: "flax_seeds", name: "Flax Seeds", protein: 18, carbs: 29, fats: 42, caloriesPerServing: 534, servingSize: "100g", servingSizeGrams: 100 },
      { id: "hemp_seeds", name: "Hemp Seeds", protein: 31, carbs: 10, fats: 48, caloriesPerServing: 553, servingSize: "100g", servingSizeGrams: 100 },
      { id: "sesame_seeds", name: "Sesame Seeds", protein: 17, carbs: 23, fats: 50, caloriesPerServing: 573, servingSize: "100g", servingSizeGrams: 100 },
    ],
  },
  {
    name: "Healthy Fats",
    items: [
      { id: "olive_oil", name: "Olive Oil", protein: 0, carbs: 0, fats: 14, caloriesPerServing: 119, servingSize: "1 tbsp (14g)", servingSizeGrams: 14 },
      { id: "coconut_oil", name: "Coconut Oil", protein: 0, carbs: 0, fats: 14, caloriesPerServing: 121, servingSize: "1 tbsp (14g)", servingSizeGrams: 14 },
      { id: "avocado_oil", name: "Avocado Oil", protein: 0, carbs: 0, fats: 14, caloriesPerServing: 124, servingSize: "1 tbsp (14g)", servingSizeGrams: 14 },
      { id: "butter", name: "Butter", protein: 0.1, carbs: 0.1, fats: 11.5, caloriesPerServing: 102, servingSize: "1 tbsp (14g)", servingSizeGrams: 14 },
      { id: "almond_butter", name: "Almond Butter", protein: 3.5, carbs: 3, fats: 9, caloriesPerServing: 98, servingSize: "16g (1 tbsp)", servingSizeGrams: 16 },
      { id: "peanut_butter", name: "Peanut Butter", protein: 4, carbs: 3, fats: 8, caloriesPerServing: 94, servingSize: "16g (1 tbsp)", servingSizeGrams: 16 },
      { id: "ghee", name: "Ghee", protein: 0, carbs: 0, fats: 14, caloriesPerServing: 123, servingSize: "1 tbsp (14g)", servingSizeGrams: 14 },
      { id: "tahini", name: "Tahini", protein: 2.6, carbs: 3, fats: 8, caloriesPerServing: 89, servingSize: "15g (1 tbsp)", servingSizeGrams: 15 },
      { id: "flaxseed_oil", name: "Flaxseed Oil", protein: 0, carbs: 0, fats: 14, caloriesPerServing: 120, servingSize: "1 tbsp (14g)", servingSizeGrams: 14 },
      { id: "walnut_oil", name: "Walnut Oil", protein: 0, carbs: 0, fats: 14, caloriesPerServing: 120, servingSize: "1 tbsp (14g)", servingSizeGrams: 14 },
      { id: "mct_oil", name: "MCT Oil", protein: 0, carbs: 0, fats: 14, caloriesPerServing: 120, servingSize: "1 tbsp (14g)", servingSizeGrams: 14 },
      { id: "cashew_butter", name: "Cashew Butter", protein: 3, carbs: 4, fats: 8, caloriesPerServing: 94, servingSize: "16g (1 tbsp)", servingSizeGrams: 16 },
      { id: "sunbutter", name: "Sunflower Seed Butter", protein: 3, carbs: 4, fats: 7, caloriesPerServing: 93, servingSize: "16g (1 tbsp)", servingSizeGrams: 16 },
      { id: "hazelnut_butter", name: "Hazelnut Butter", protein: 2, carbs: 2, fats: 11, caloriesPerServing: 101, servingSize: "16g (1 tbsp)", servingSizeGrams: 16 },
      { id: "coconut_butter", name: "Coconut Butter", protein: 2, carbs: 4, fats: 10, caloriesPerServing: 105, servingSize: "16g (1 tbsp)", servingSizeGrams: 16 },
    ],
  },
  {
    name: "Condiments & Sauces",
    items: [
      { id: "ketchup", name: "Ketchup", protein: 1, carbs: 6, fats: 0.1, caloriesPerServing: 29, servingSize: "17g (1 tbsp)", servingSizeGrams: 17 },
      { id: "mustard", name: "Mustard (yellow)", protein: 1, carbs: 1, fats: 0.5, caloriesPerServing: 10, servingSize: "10g (1 tbsp)", servingSizeGrams: 10 },
      { id: "mayo", name: "Mayonnaise", protein: 0.1, carbs: 0.4, fats: 11, caloriesPerServing: 94, servingSize: "13g (1 tbsp)", servingSizeGrams: 13 },
      { id: "hummus", name: "Hummus", protein: 2, carbs: 4, fats: 2, caloriesPerServing: 27, servingSize: "15g (1 tbsp)", servingSizeGrams: 15 },
      { id: "salsa", name: "Salsa", protein: 0.4, carbs: 3, fats: 0.1, caloriesPerServing: 14, servingSize: "30g (2 tbsp)", servingSizeGrams: 30 },
      { id: "guacamole", name: "Guacamole", protein: 1, carbs: 5, fats: 7, caloriesPerServing: 77, servingSize: "50g (2 tbsp)", servingSizeGrams: 50 },
      { id: "soy_sauce", name: "Soy Sauce", protein: 1.3, carbs: 1.3, fats: 0, caloriesPerServing: 8, servingSize: "15ml (1 tbsp)", servingSizeGrams: 15 },
      { id: "hot_sauce", name: "Hot Sauce", protein: 0.3, carbs: 0.7, fats: 0, caloriesPerServing: 5, servingSize: "15ml (1 tbsp)", servingSizeGrams: 15 },
      { id: "bbq_sauce", name: "BBQ Sauce", protein: 0.2, carbs: 10, fats: 0.1, caloriesPerServing: 40, servingSize: "17g (1 tbsp)", servingSizeGrams: 17 },
      { id: "ranch", name: "Ranch Dressing", protein: 0.2, carbs: 1.5, fats: 7.7, caloriesPerServing: 73, servingSize: "15g (1 tbsp)", servingSizeGrams: 15 },
      { id: "italian_dressing", name: "Italian Dressing", protein: 0.1, carbs: 2, fats: 7, caloriesPerServing: 70, servingSize: "15g (1 tbsp)", servingSizeGrams: 15 },
      { id: "pesto", name: "Pesto", protein: 1.5, carbs: 1, fats: 8, caloriesPerServing: 81, servingSize: "15g (1 tbsp)", servingSizeGrams: 15 },
      { id: "dijon", name: "Dijon Mustard", protein: 1, carbs: 0.9, fats: 0.5, caloriesPerServing: 10, servingSize: "10g (1 tbsp)", servingSizeGrams: 10 },
      { id: "honey_mustard", name: "Honey Mustard", protein: 0.5, carbs: 3, fats: 3, caloriesPerServing: 41, servingSize: "15g (1 tbsp)", servingSizeGrams: 15 },
      { id: "tzatziki", name: "Tzatziki", protein: 0.6, carbs: 1.5, fats: 2, caloriesPerServing: 27, servingSize: "30g (2 tbsp)", servingSizeGrams: 30 },
      { id: "marinara", name: "Marinara Sauce", protein: 1, carbs: 5, fats: 2, caloriesPerServing: 40, servingSize: "60g (1/4 cup)", servingSizeGrams: 60 },
      { id: "teriyaki", name: "Teriyaki Sauce", protein: 1, carbs: 8, fats: 0, caloriesPerServing: 36, servingSize: "17g (1 tbsp)", servingSizeGrams: 17 },
      { id: "worcestershire", name: "Worcestershire Sauce", protein: 0, carbs: 3, fats: 0, caloriesPerServing: 12, servingSize: "17g (1 tbsp)", servingSizeGrams: 17 },
      { id: "vinegar_balsamic", name: "Balsamic Vinegar", protein: 0.5, carbs: 6, fats: 0, caloriesPerServing: 28, servingSize: "16g (1 tbsp)", servingSizeGrams: 16 },
      { id: "vinegar_apple", name: "Apple Cider Vinegar", protein: 0, carbs: 0.1, fats: 0, caloriesPerServing: 3, servingSize: "15g (1 tbsp)", servingSizeGrams: 15 },
      { id: "coconut_aminos", name: "Coconut Aminos", protein: 0, carbs: 3, fats: 0, caloriesPerServing: 15, servingSize: "15ml (1 tbsp)", servingSizeGrams: 15 },
      { id: "aioli", name: "Aioli", protein: 0.2, carbs: 0.5, fats: 12, caloriesPerServing: 100, servingSize: "14g (1 tbsp)", servingSizeGrams: 14 },
      { id: "tapenade", name: "Olive Tapenade", protein: 0.5, carbs: 2, fats: 10, caloriesPerServing: 100, servingSize: "20g (1 tbsp)", servingSizeGrams: 20 },
      { id: "kewpie", name: "Kewpie Mayo", protein: 0.2, carbs: 0.5, fats: 11, caloriesPerServing: 98, servingSize: "13g (1 tbsp)", servingSizeGrams: 13 },
      { id: "chimichurri", name: "Chimichurri", protein: 0.2, carbs: 1, fats: 7, caloriesPerServing: 67, servingSize: "15g (1 tbsp)", servingSizeGrams: 15 },
    ],
  },
  {
    name: "Beverages",
    items: [
      { id: "water", name: "Water", protein: 0, carbs: 0, fats: 0, caloriesPerServing: 0, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "coffee", name: "Coffee (black)", protein: 0.3, carbs: 0, fats: 0, caloriesPerServing: 2, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "tea_green", name: "Green Tea", protein: 0, carbs: 0, fats: 0, caloriesPerServing: 2, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "tea_black", name: "Black Tea", protein: 0, carbs: 0, fats: 0, caloriesPerServing: 2, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "tea_herbal", name: "Herbal Tea", protein: 0, carbs: 0, fats: 0, caloriesPerServing: 2, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "sparkling_water", name: "Sparkling Water", protein: 0, carbs: 0, fats: 0, caloriesPerServing: 0, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "coconut_water", name: "Coconut Water", protein: 0.7, carbs: 9, fats: 0, caloriesPerServing: 43, servingSize: "240ml cup", servingSizeGrams: 240 },
      { id: "protein_shake", name: "Protein Shake", protein: 24, carbs: 3, fats: 1, caloriesPerServing: 120, servingSize: "30g scoop", servingSizeGrams: 30 },
      { id: "kombucha", name: "Kombucha", protein: 0.3, carbs: 7, fats: 0, caloriesPerServing: 30, servingSize: "240ml", servingSizeGrams: 240 },
      { id: "smoothie_green", name: "Green Smoothie", protein: 3, carbs: 20, fats: 1, caloriesPerServing: 100, servingSize: "240ml", servingSizeGrams: 240 },
      { id: "smoothie_fruit", name: "Fruit Smoothie", protein: 2, carbs: 30, fats: 1, caloriesPerServing: 140, servingSize: "240ml", servingSizeGrams: 240 },
      { id: "juice_orange", name: "Orange Juice", protein: 1, carbs: 21, fats: 0.2, caloriesPerServing: 84, servingSize: "240ml", servingSizeGrams: 240 },
      { id: "juice_apple", name: "Apple Juice", protein: 0.2, carbs: 28, fats: 0.3, caloriesPerServing: 114, servingSize: "240ml", servingSizeGrams: 240 },
      { id: "juice_cranberry", name: "Cranberry Juice", protein: 0.3, carbs: 31, fats: 0.1, caloriesPerServing: 117, servingSize: "240ml", servingSizeGrams: 240 },
      { id: "matcha", name: "Matcha Tea", protein: 0.7, carbs: 0.4, fats: 0.1, caloriesPerServing: 5, servingSize: "240ml", servingSizeGrams: 240 },
    ],
  },
  {
    name: "Spices & Herbs",
    items: [
      { id: "salt", name: "Salt", protein: 0, carbs: 0, fats: 0, caloriesPerServing: 0, servingSize: "1g", servingSizeGrams: 1 },
      { id: "black_pepper", name: "Black Pepper", protein: 0.1, carbs: 0.6, fats: 0.1, caloriesPerServing: 2, servingSize: "1g", servingSizeGrams: 1 },
      { id: "oregano", name: "Oregano", protein: 0.3, carbs: 0.7, fats: 0.1, caloriesPerServing: 2, servingSize: "1g", servingSizeGrams: 1 },
      { id: "basil", name: "Basil", protein: 0.3, carbs: 0.5, fats: 0.1, caloriesPerServing: 2, servingSize: "1g", servingSizeGrams: 1 },
      { id: "thyme", name: "Thyme", protein: 0.3, carbs: 0.6, fats: 0.1, caloriesPerServing: 2, servingSize: "1g", servingSizeGrams: 1 },
      { id: "cinnamon", name: "Cinnamon", protein: 0.1, carbs: 0.8, fats: 0.1, caloriesPerServing: 2, servingSize: "1g", servingSizeGrams: 1 },
      { id: "cumin", name: "Cumin", protein: 0.2, carbs: 0.6, fats: 0.2, caloriesPerServing: 4, servingSize: "1g", servingSizeGrams: 1 },
      { id: "paprika", name: "Paprika", protein: 0.2, carbs: 0.6, fats: 0.1, caloriesPerServing: 2, servingSize: "1g", servingSizeGrams: 1 },
      { id: "turmeric", name: "Turmeric", protein: 0.1, carbs: 0.7, fats: 0.1, caloriesPerServing: 3, servingSize: "1g", servingSizeGrams: 1 },
      { id: "rosemary", name: "Rosemary", protein: 0.1, carbs: 0.7, fats: 0.2, caloriesPerServing: 4, servingSize: "1g", servingSizeGrams: 1 },
      { id: "cayenne", name: "Cayenne Pepper", protein: 0.1, carbs: 0.6, fats: 0.1, caloriesPerServing: 2, servingSize: "1g", servingSizeGrams: 1 },
      { id: "sage", name: "Sage", protein: 0.2, carbs: 0.6, fats: 0.1, caloriesPerServing: 2, servingSize: "1g", servingSizeGrams: 1 },
      { id: "mint", name: "Mint", protein: 0.1, carbs: 0.5, fats: 0, caloriesPerServing: 2, servingSize: "1g", servingSizeGrams: 1 },
      { id: "bay_leaf", name: "Bay Leaf", protein: 0.1, carbs: 0.8, fats: 0.1, caloriesPerServing: 2, servingSize: "1g", servingSizeGrams: 1 },
      { id: "parsley", name: "Parsley", protein: 0.3, carbs: 0.6, fats: 0.1, caloriesPerServing: 4, servingSize: "10g", servingSizeGrams: 10 },
      { id: "cilantro", name: "Cilantro/Coriander", protein: 0.2, carbs: 0.4, fats: 0.1, caloriesPerServing: 2, servingSize: "10g", servingSizeGrams: 10 },
      { id: "dill", name: "Dill", protein: 0.3, carbs: 0.7, fats: 0.1, caloriesPerServing: 4, servingSize: "10g", servingSizeGrams: 10 },
      { id: "fennel_seed", name: "Fennel Seed", protein: 0.2, carbs: 0.7, fats: 0.1, caloriesPerServing: 3, servingSize: "1g", servingSizeGrams: 1 },
      { id: "cardamom", name: "Cardamom", protein: 0.1, carbs: 0.7, fats: 0.1, caloriesPerServing: 3, servingSize: "1g", servingSizeGrams: 1 },
      { id: "nutmeg", name: "Nutmeg", protein: 0.1, carbs: 0.5, fats: 0.4, caloriesPerServing: 5, servingSize: "1g", servingSizeGrams: 1 },
    ],
  },
];

